#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := PowerSpy

EXTRA_COMPONENT_DIRS := /C/Users/ADM/Documents/Eagle/projects/PowerSpy/Firmware/esp-idf-lib/components

include $(IDF_PATH)/make/project.mk

